# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_about(object):
    def setupUi(self, about):
        about.setObjectName("about")
        about.resize(586, 258)
        self.label = QtWidgets.QLabel(parent=about)
        self.label.setGeometry(QtCore.QRect(230, 30, 131, 121))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/app.ico"))
        self.label.setObjectName("label")
        self.okButton = QtWidgets.QPushButton(parent=about)
        self.okButton.setGeometry(QtCore.QRect(470, 210, 75, 24))
        self.okButton.setObjectName("okButton")
        self.label_2 = QtWidgets.QLabel(parent=about)
        self.label_2.setGeometry(QtCore.QRect(60, 160, 451, 41))
        self.label_2.setAutoFillBackground(False)
        self.label_2.setLineWidth(2)
        self.label_2.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(about)
        QtCore.QMetaObject.connectSlotsByName(about)

    def retranslateUi(self, about):
        _translate = QtCore.QCoreApplication.translate
        about.setWindowTitle(_translate("about", "About"))
        self.okButton.setText(_translate("about", "OK"))
        self.label_2.setText(_translate("about", "RookEye.ph is a computer vision project dedicated to recording chess moves."))
