# Form implementation generated from reading ui file 'newGame.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_newGame(object):
    def setupUi(self, newGame):
        newGame.setObjectName("newGame")
        newGame.resize(400, 627)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/app.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        newGame.setWindowIcon(icon)
        self.okButton = QtWidgets.QDialogButtonBox(parent=newGame)
        self.okButton.setGeometry(QtCore.QRect(40, 580, 341, 32))
        self.okButton.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.okButton.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.okButton.setObjectName("okButton")
        self.label = QtWidgets.QLabel(parent=newGame)
        self.label.setGeometry(QtCore.QRect(40, 50, 49, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=newGame)
        self.label_2.setGeometry(QtCore.QRect(40, 90, 49, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=newGame)
        self.label_3.setGeometry(QtCore.QRect(40, 120, 49, 16))
        self.label_3.setObjectName("label_3")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=newGame)
        self.plainTextEdit.setGeometry(QtCore.QRect(80, 50, 241, 31))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(parent=newGame)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(90, 90, 241, 31))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(parent=newGame)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(90, 130, 241, 31))
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.calibrateCameraButton = QtWidgets.QPushButton(parent=newGame)
        self.calibrateCameraButton.setGeometry(QtCore.QRect(100, 200, 141, 24))
        self.calibrateCameraButton.setObjectName("calibrateCameraButton")

        self.retranslateUi(newGame)
        self.okButton.accepted.connect(newGame.accept) # type: ignore
        self.okButton.rejected.connect(newGame.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(newGame)

    def retranslateUi(self, newGame):
        _translate = QtCore.QCoreApplication.translate
        newGame.setWindowTitle(_translate("newGame", "New Game"))
        self.label.setText(_translate("newGame", "Game:"))
        self.label_2.setText(_translate("newGame", "Player 1:"))
        self.label_3.setText(_translate("newGame", "Player 2:"))
        self.calibrateCameraButton.setText(_translate("newGame", "Calibrate Camera"))
