# Form implementation generated from reading ui file 'viewHistory.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_viewHistory(object):
    def setupUi(self, viewHistory):
        viewHistory.setObjectName("viewHistory")
        viewHistory.resize(989, 743)
        self.centralwidget = QtWidgets.QWidget(parent=viewHistory)
        self.centralwidget.setObjectName("centralwidget")
        self.chessOutput = QtWidgets.QLabel(parent=self.centralwidget)
        self.chessOutput.setGeometry(QtCore.QRect(40, 40, 541, 611))
        self.chessOutput.setText("")
        self.chessOutput.setObjectName("chessOutput")
        self.matchList = QtWidgets.QListWidget(parent=self.centralwidget)
        self.matchList.setGeometry(QtCore.QRect(650, 90, 256, 91))
        self.matchList.setObjectName("matchList")
        self.loadButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.loadButton.setGeometry(QtCore.QRect(730, 200, 75, 24))
        self.loadButton.setObjectName("loadButton")
        self.movesList = QtWidgets.QListWidget(parent=self.centralwidget)
        self.movesList.setGeometry(QtCore.QRect(650, 300, 256, 192))
        self.movesList.setObjectName("movesList")
        self.labelMovesList = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelMovesList.setGeometry(QtCore.QRect(740, 270, 61, 16))
        self.labelMovesList.setObjectName("labelMovesList")
        self.returnButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.returnButton.setGeometry(QtCore.QRect(650, 540, 251, 24))
        self.returnButton.setObjectName("returnButton")
        viewHistory.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=viewHistory)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 989, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOptions = QtWidgets.QMenu(parent=self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        self.menuHelp = QtWidgets.QMenu(parent=self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        viewHistory.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=viewHistory)
        self.statusbar.setObjectName("statusbar")
        viewHistory.setStatusBar(self.statusbar)
        self.actionNew_Game = QtGui.QAction(parent=viewHistory)
        self.actionNew_Game.setObjectName("actionNew_Game")
        self.actionOpen_CSV = QtGui.QAction(parent=viewHistory)
        self.actionOpen_CSV.setObjectName("actionOpen_CSV")
        self.actionExport_CSV = QtGui.QAction(parent=viewHistory)
        self.actionExport_CSV.setObjectName("actionExport_CSV")
        self.actionReport_Issue = QtGui.QAction(parent=viewHistory)
        self.actionReport_Issue.setObjectName("actionReport_Issue")
        self.actionAbout = QtGui.QAction(parent=viewHistory)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionNew_Game)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen_CSV)
        self.menuFile.addAction(self.actionExport_CSV)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(viewHistory)
        QtCore.QMetaObject.connectSlotsByName(viewHistory)

    def retranslateUi(self, viewHistory):
        _translate = QtCore.QCoreApplication.translate
        viewHistory.setWindowTitle(_translate("viewHistory", "History"))
        self.loadButton.setText(_translate("viewHistory", "Load Match"))
        self.labelMovesList.setText(_translate("viewHistory", "Moves List"))
        self.returnButton.setText(_translate("viewHistory", "Return"))
        self.menuFile.setTitle(_translate("viewHistory", "File"))
        self.menuOptions.setTitle(_translate("viewHistory", "Options"))
        self.menuHelp.setTitle(_translate("viewHistory", "Help"))
        self.actionNew_Game.setText(_translate("viewHistory", "New Game"))
        self.actionOpen_CSV.setText(_translate("viewHistory", "Open CSV"))
        self.actionExport_CSV.setText(_translate("viewHistory", "Export CSV"))
        self.actionReport_Issue.setText(_translate("viewHistory", "Report Issue"))
        self.actionAbout.setText(_translate("viewHistory", "About "))
