# Form implementation generated from reading ui file 'viewHistory.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_viewHistory(object):
    def setupUi(self, viewHistory):
        viewHistory.setObjectName("viewHistory")
        viewHistory.resize(800, 601)
        self.centralwidget = QtWidgets.QWidget(parent=viewHistory)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(50, 100, 381, 341))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.listView = QtWidgets.QListView(parent=self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(120, 480, 256, 41))
        self.listView.setObjectName("listView")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 490, 91, 16))
        self.label.setObjectName("label")
        self.graphicsView = QtWidgets.QGraphicsView(parent=self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(480, 40, 256, 471))
        self.graphicsView.setObjectName("graphicsView")
        viewHistory.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=viewHistory)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOptions = QtWidgets.QMenu(parent=self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        self.menuHelp = QtWidgets.QMenu(parent=self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        viewHistory.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=viewHistory)
        self.statusbar.setObjectName("statusbar")
        viewHistory.setStatusBar(self.statusbar)
        self.actionNew_Game = QtGui.QAction(parent=viewHistory)
        self.actionNew_Game.setObjectName("actionNew_Game")
        self.actionOpen_CSV = QtGui.QAction(parent=viewHistory)
        self.actionOpen_CSV.setObjectName("actionOpen_CSV")
        self.actionExport_CSV = QtGui.QAction(parent=viewHistory)
        self.actionExport_CSV.setObjectName("actionExport_CSV")
        self.actionReport_Issue = QtGui.QAction(parent=viewHistory)
        self.actionReport_Issue.setObjectName("actionReport_Issue")
        self.actionAbout = QtGui.QAction(parent=viewHistory)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionNew_Game)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen_CSV)
        self.menuFile.addAction(self.actionExport_CSV)
        self.menuHelp.addAction(self.actionReport_Issue)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(viewHistory)
        QtCore.QMetaObject.connectSlotsByName(viewHistory)

    def retranslateUi(self, viewHistory):
        _translate = QtCore.QCoreApplication.translate
        viewHistory.setWindowTitle(_translate("viewHistory", "History"))
        self.label.setText(_translate("viewHistory", "Recent Matches"))
        self.menuFile.setTitle(_translate("viewHistory", "File"))
        self.menuOptions.setTitle(_translate("viewHistory", "Options"))
        self.menuHelp.setTitle(_translate("viewHistory", "Help"))
        self.actionNew_Game.setText(_translate("viewHistory", "New Game"))
        self.actionOpen_CSV.setText(_translate("viewHistory", "Open CSV"))
        self.actionExport_CSV.setText(_translate("viewHistory", "Export CSV"))
        self.actionReport_Issue.setText(_translate("viewHistory", "Report Issue"))
        self.actionAbout.setText(_translate("viewHistory", "About "))
