# Form implementation generated from reading ui file 'calibration.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_calibrateCamera(object):
    def setupUi(self, calibrateCamera):
        calibrateCamera.setObjectName("calibrateCamera")
        calibrateCamera.resize(568, 471)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=calibrateCamera)
        self.buttonBox.setGeometry(QtCore.QRect(190, 410, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.imageOutput = QtWidgets.QLabel(parent=calibrateCamera)
        self.imageOutput.setGeometry(QtCore.QRect(50, 30, 471, 341))
        self.imageOutput.setText("")
        self.imageOutput.setObjectName("imageOutput")

        self.retranslateUi(calibrateCamera)
        self.buttonBox.accepted.connect(calibrateCamera.accept) # type: ignore
        self.buttonBox.rejected.connect(calibrateCamera.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(calibrateCamera)

    def retranslateUi(self, calibrateCamera):
        _translate = QtCore.QCoreApplication.translate
        calibrateCamera.setWindowTitle(_translate("calibrateCamera", "Calibration"))
