# Form implementation generated from reading ui file 'ui\chessGame.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtSvgWidgets import QSvgWidget

class Ui_ChessGameWindow(object):
    def setupUi(self, ChessGameWindow):
        ChessGameWindow.setObjectName("ChessGameWindow")
        ChessGameWindow.resize(900, 700)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\../img/app.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        ChessGameWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=ChessGameWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.outerVerticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.outerVerticalLayout.setObjectName("outerVerticalLayout")
        self.headerLayout = QtWidgets.QHBoxLayout()
        self.headerLayout.setObjectName("headerLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.headerLayout.addItem(spacerItem)
        self.gameInfoGroup = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.gameInfoGroup.setStyleSheet("\n"
"           QGroupBox {\n"
"            border: 1px solid #ccc;\n"
"            border-radius: 5px;\n"
"            margin-top: 10px;\n"
"           }\n"
"           QGroupBox::title {\n"
"            subcontrol-origin: margin;\n"
"            left: 10px;\n"
"            padding: 0 3px;\n"
"           }\n"
"         ")
        self.gameInfoGroup.setObjectName("gameInfoGroup")
        self.verticalGameInfoLayout = QtWidgets.QVBoxLayout(self.gameInfoGroup)
        self.verticalGameInfoLayout.setObjectName("verticalGameInfoLayout")
        self.gameInfoLayout = QtWidgets.QHBoxLayout()
        self.gameInfoLayout.setObjectName("gameInfoLayout")
        self.gameNameLabel = QtWidgets.QLabel(parent=self.gameInfoGroup)
        self.gameNameLabel.setStyleSheet("\n"
"                font-weight: bold;\n"
"                font-size: 14px;\n"
"                padding: 5px;\n"
"              ")
        self.gameNameLabel.setObjectName("gameNameLabel")
        self.gameInfoLayout.addWidget(self.gameNameLabel)
        self.roundLabel = QtWidgets.QLabel(parent=self.gameInfoGroup)
        self.roundLabel.setStyleSheet("\n"
"                font-weight: bold;\n"
"                font-size: 14px;\n"
"                padding: 5px;\n"
"              ")
        self.roundLabel.setObjectName("roundLabel")
        self.gameInfoLayout.addWidget(self.roundLabel)
        self.verticalGameInfoLayout.addLayout(self.gameInfoLayout)
        self.siteLabel = QtWidgets.QLabel(parent=self.gameInfoGroup)
        self.siteLabel.setStyleSheet("\n"
"              font-size: 12px;\n"
"              padding: 2px;\n"
"              color: #666;\n"
"            ")
        self.siteLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.siteLabel.setObjectName("siteLabel")
        self.verticalGameInfoLayout.addWidget(self.siteLabel)
        self.headerLayout.addWidget(self.gameInfoGroup)
        self.statusGroup = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.statusGroup.setStyleSheet("\n"
"           QGroupBox {\n"
"            border: 1px solid #ccc;\n"
"            border-radius: 5px;\n"
"            margin-top: 10px;\n"
"           }\n"
"           QGroupBox::title {\n"
"            subcontrol-origin: margin;\n"
"            left: 10px;\n"
"            padding: 0 3px;\n"
"           }\n"
"         ")
        self.statusGroup.setObjectName("statusGroup")
        self.verticalStatusLayout = QtWidgets.QVBoxLayout(self.statusGroup)
        self.verticalStatusLayout.setObjectName("verticalStatusLayout")
        self.chessboardStatusLayout = QtWidgets.QHBoxLayout()
        self.chessboardStatusLayout.setObjectName("chessboardStatusLayout")
        self.chessboardStatusIndicator = QtWidgets.QLabel(parent=self.statusGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chessboardStatusIndicator.sizePolicy().hasHeightForWidth())
        self.chessboardStatusIndicator.setSizePolicy(sizePolicy)
        self.chessboardStatusIndicator.setMinimumSize(QtCore.QSize(16, 16))
        self.chessboardStatusIndicator.setMaximumSize(QtCore.QSize(16, 16))
        self.chessboardStatusIndicator.setStyleSheet("\n"
"               background-color: #4CAF50;\n"
"               border-radius: 8px;\n"
"               min-width: 16px;\n"
"               min-height: 16px;\n"
"               max-width: 16px;\n"
"               max-height: 16px;\n"
"              ")
        self.chessboardStatusIndicator.setObjectName("chessboardStatusIndicator")
        self.chessboardStatusLayout.addWidget(self.chessboardStatusIndicator)
        spacerItem1 = QtWidgets.QSpacerItem(6, 10, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.chessboardStatusLayout.addItem(spacerItem1)
        self.chessboardStatusLabel = QtWidgets.QLabel(parent=self.statusGroup)
        self.chessboardStatusLabel.setStyleSheet("font-size: 12px; color: #666;")
        self.chessboardStatusLabel.setObjectName("chessboardStatusLabel")
        self.chessboardStatusLayout.addWidget(self.chessboardStatusLabel)
        self.verticalStatusLayout.addLayout(self.chessboardStatusLayout)
        self.gameStatusLayout = QtWidgets.QHBoxLayout()
        self.gameStatusLayout.setObjectName("gameStatusLayout")
        self.gameStatusIndicator = QtWidgets.QLabel(parent=self.statusGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gameStatusIndicator.sizePolicy().hasHeightForWidth())
        self.gameStatusIndicator.setSizePolicy(sizePolicy)
        self.gameStatusIndicator.setMinimumSize(QtCore.QSize(16, 16))
        self.gameStatusIndicator.setMaximumSize(QtCore.QSize(16, 16))
        self.gameStatusIndicator.setStyleSheet("\n"
"               background-color: #FFC107;\n"
"               border-radius: 8px;\n"
"               min-width: 16px;\n"
"               min-height: 16px;\n"
"               max-width: 16px;\n"
"               max-height: 16px;\n"
"              ")
        self.gameStatusIndicator.setObjectName("gameStatusIndicator")
        self.gameStatusLayout.addWidget(self.gameStatusIndicator)
        spacerItem2 = QtWidgets.QSpacerItem(6, 10, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gameStatusLayout.addItem(spacerItem2)
        self.gameStatusLabel = QtWidgets.QLabel(parent=self.statusGroup)
        self.gameStatusLabel.setStyleSheet("font-size: 12px; color: #666;")
        self.gameStatusLabel.setObjectName("gameStatusLabel")
        self.gameStatusLayout.addWidget(self.gameStatusLabel)
        self.verticalStatusLayout.addLayout(self.gameStatusLayout)
        self.headerLayout.addWidget(self.statusGroup)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.headerLayout.addItem(spacerItem3)
        self.outerVerticalLayout.addLayout(self.headerLayout)
        self.mainLayout = QtWidgets.QHBoxLayout()
        self.mainLayout.setObjectName("mainLayout")
        self.leftLayout = QtWidgets.QVBoxLayout()
        self.leftLayout.setObjectName("leftLayout")
        self.chessboard = QSvgWidget(parent=self.centralwidget)
        self.chessboard.setMinimumSize(QtCore.QSize(480, 480))
        self.chessboard.setMaximumSize(QtCore.QSize(480, 480))
        self.chessboard.setStyleSheet("border: 2px solid #333; background: white;")
        self.chessboard.setObjectName("chessboard")
        self.leftLayout.addWidget(self.chessboard)
        self.mainLayout.addLayout(self.leftLayout)
        self.rightLayout = QtWidgets.QVBoxLayout()
        self.rightLayout.setObjectName("rightLayout")
        self.player1Group = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.player1Group.setObjectName("player1Group")
        self.player1Layout = QtWidgets.QVBoxLayout(self.player1Group)
        self.player1Layout.setObjectName("player1Layout")
        self.player1Name = QtWidgets.QLineEdit(parent=self.player1Group)
        self.player1Name.setStyleSheet("\n"
"                padding: 1px;\n"
"                font-size: 13px;\n"
"                background: #f8f8f8;\n"
"                border: 1px solid #ddd;\n"
"                color: #333;\n"
"              ")
        self.player1Name.setReadOnly(True)
        self.player1Name.setObjectName("player1Name")
        self.player1Layout.addWidget(self.player1Name)
        self.player1listView = QtWidgets.QListView(parent=self.player1Group)
        self.player1listView.setMinimumSize(QtCore.QSize(0, 80))
        self.player1listView.setMaximumSize(QtCore.QSize(16777215, 80))
        self.player1listView.setStyleSheet("\n"
"                QListView {\n"
"                 background: #f8f8f8;\n"
"                 border: 1px solid #ddd;\n"
"                 border-radius: 2px;\n"
"                 padding: 1px;\n"
"                }\n"
"              ")
        self.player1listView.setObjectName("player1listView")
        self.player1Layout.addWidget(self.player1listView)
        self.rightLayout.addWidget(self.player1Group)
        self.player2Group = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.player2Group.setObjectName("player2Group")
        self.player2Layout = QtWidgets.QVBoxLayout(self.player2Group)
        self.player2Layout.setObjectName("player2Layout")
        self.player2Name = QtWidgets.QLineEdit(parent=self.player2Group)
        self.player2Name.setStyleSheet("\n"
"                padding: 1px;\n"
"                font-size: 13px;\n"
"                background: #f8f8f8;\n"
"                border: 1px solid #ddd;\n"
"                color: #333;\n"
"              ")
        self.player2Name.setReadOnly(True)
        self.player2Name.setObjectName("player2Name")
        self.player2Layout.addWidget(self.player2Name)
        self.player2listView = QtWidgets.QListView(parent=self.player2Group)
        self.player2listView.setMinimumSize(QtCore.QSize(0, 80))
        self.player2listView.setMaximumSize(QtCore.QSize(16777215, 80))
        self.player2listView.setStyleSheet("\n"
"                QListView {\n"
"                 background: #f8f8f8;\n"
"                 border: 1px solid #ddd;\n"
"                 border-radius: 2px;\n"
"                 padding: 1px;\n"
"                }\n"
"              ")
        self.player2listView.setObjectName("player2listView")
        self.player2Layout.addWidget(self.player2listView)
        self.rightLayout.addWidget(self.player2Group)
        self.endButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.endButton.setStyleSheet("\n"
"             QPushButton {\n"
"              background: #d9534f;\n"
"              color: white;\n"
"              border: none;\n"
"              padding: 8px 16px;\n"
"              border-radius: 4px;\n"
"              font-weight: bold;\n"
"             }\n"
"             QPushButton:hover {\n"
"              background: #c9302c;\n"
"             }\n"
"            ")
        self.endButton.setObjectName("endButton")
        self.rightLayout.addWidget(self.endButton)
        self.mainLayout.addLayout(self.rightLayout)
        self.outerVerticalLayout.addLayout(self.mainLayout)
        ChessGameWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ChessGameWindow)
        QtCore.QMetaObject.connectSlotsByName(ChessGameWindow)

    def retranslateUi(self, ChessGameWindow):
        _translate = QtCore.QCoreApplication.translate
        ChessGameWindow.setWindowTitle(_translate("ChessGameWindow", "Chess Game"))
        self.gameInfoGroup.setTitle(_translate("ChessGameWindow", "Game Information"))
        self.gameNameLabel.setText(_translate("ChessGameWindow", "Game: "))
        self.roundLabel.setText(_translate("ChessGameWindow", "Round: "))
        self.siteLabel.setText(_translate("ChessGameWindow", "Site: "))
        self.statusGroup.setTitle(_translate("ChessGameWindow", "Status Indicators"))
        self.chessboardStatusLabel.setText(_translate("ChessGameWindow", "Chessboard Mapped"))
        self.gameStatusLabel.setText(_translate("ChessGameWindow", "Game Active"))
        self.player1Group.setTitle(_translate("ChessGameWindow", "White Player"))
        self.player2Group.setTitle(_translate("ChessGameWindow", "Black Player"))
        self.endButton.setText(_translate("ChessGameWindow", "End Game"))