# Form implementation generated from reading ui file 'ui\chessGame.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtSvgWidgets import QSvgWidget

class Ui_ChessGameWindow(object):
    def setupUi(self, ChessGameWindow):
        ChessGameWindow.setObjectName("ChessGameWindow")
        ChessGameWindow.resize(1000, 932)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\../img/app.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        ChessGameWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=ChessGameWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.outerVerticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.outerVerticalLayout.setObjectName("outerVerticalLayout")
        self.headerLayout = QtWidgets.QHBoxLayout()
        self.headerLayout.setObjectName("headerLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.headerLayout.addItem(spacerItem)
        self.gameInfoGroup = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.gameInfoGroup.setStyleSheet("\n"
"           QGroupBox {\n"
"            border: 1px solid #ccc;\n"
"            border-radius: 5px;\n"
"            margin-top: 10px;\n"
"           }\n"
"           QGroupBox::title {\n"
"            subcontrol-origin: margin;\n"
"            left: 10px;\n"
"            padding: 0 3px;\n"
"           }\n"
"         ")
        self.gameInfoGroup.setObjectName("gameInfoGroup")
        self.verticalGameInfoLayout = QtWidgets.QVBoxLayout(self.gameInfoGroup)
        self.verticalGameInfoLayout.setObjectName("verticalGameInfoLayout")
        self.gameInfoLayout = QtWidgets.QHBoxLayout()
        self.gameInfoLayout.setObjectName("gameInfoLayout")
        self.gameNameLabel = QtWidgets.QLabel(parent=self.gameInfoGroup)
        self.gameNameLabel.setStyleSheet("\n"
"                font-weight: bold;\n"
"                font-size: 14px;\n"
"                padding: 5px;\n"
"              ")
        self.gameNameLabel.setObjectName("gameNameLabel")
        self.gameInfoLayout.addWidget(self.gameNameLabel)
        self.roundLabel = QtWidgets.QLabel(parent=self.gameInfoGroup)
        self.roundLabel.setStyleSheet("\n"
"                font-weight: bold;\n"
"                font-size: 14px;\n"
"                padding: 5px;\n"
"              ")
        self.roundLabel.setObjectName("roundLabel")
        self.gameInfoLayout.addWidget(self.roundLabel)
        self.verticalGameInfoLayout.addLayout(self.gameInfoLayout)
        self.siteLabel = QtWidgets.QLabel(parent=self.gameInfoGroup)
        self.siteLabel.setStyleSheet("\n"
"              font-size: 12px;\n"
"              padding: 2px;\n"
"              color: #666;\n"
"            ")
        self.siteLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.siteLabel.setObjectName("siteLabel")
        self.verticalGameInfoLayout.addWidget(self.siteLabel)
        self.headerLayout.addWidget(self.gameInfoGroup)
        self.statusIndicatorsLayout = QtWidgets.QVBoxLayout()
        self.statusIndicatorsLayout.setObjectName("statusIndicatorsLayout")
        self.chessboardStatusIndicator = QtWidgets.QLabel(parent=self.centralwidget)
        self.chessboardStatusIndicator.setStyleSheet("\n"
"            background-color: #4CAF50;  /* Green color */\n"
"            border-radius: 5px;\n"
"            min-width: 10px;\n"
"            min-height: 10px;\n"
"            max-width: 10px;\n"
"            max-height: 10px;\n"
"           ")
        self.chessboardStatusIndicator.setObjectName("chessboardStatusIndicator")
        self.statusIndicatorsLayout.addWidget(self.chessboardStatusIndicator)
        self.gameStatusIndicator = QtWidgets.QLabel(parent=self.centralwidget)
        self.gameStatusIndicator.setStyleSheet("\n"
"            background-color: #FFC107;  /* Yellow color */\n"
"            border-radius: 5px;\n"
"            min-width: 10px;\n"
"            min-height: 10px;\n"
"            max-width: 10px;\n"
"            max-height: 10px;\n"
"           ")
        self.gameStatusIndicator.setObjectName("gameStatusIndicator")
        self.statusIndicatorsLayout.addWidget(self.gameStatusIndicator)
        self.headerLayout.addLayout(self.statusIndicatorsLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.headerLayout.addItem(spacerItem1)
        self.outerVerticalLayout.addLayout(self.headerLayout)
        self.mainLayout = QtWidgets.QHBoxLayout()
        self.mainLayout.setObjectName("mainLayout")
        self.leftLayout = QtWidgets.QVBoxLayout()
        self.leftLayout.setObjectName("leftLayout")
        self.chessboard = QSvgWidget(parent=self.centralwidget)
        self.chessboard.setMinimumSize(QtCore.QSize(500, 500))
        self.chessboard.setStyleSheet("border: 2px solid #333; background: white;")
        self.chessboard.setObjectName("chessboard")
        self.leftLayout.addWidget(self.chessboard)
        self.appIcon = QtWidgets.QLabel(parent=self.centralwidget)
        self.appIcon.setStyleSheet("padding: 20px;")
        self.appIcon.setPixmap(QtGui.QPixmap("ui\\../img/rookeye.ph.png"))
        self.appIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.appIcon.setObjectName("appIcon")
        self.leftLayout.addWidget(self.appIcon)
        self.mainLayout.addLayout(self.leftLayout)
        self.rightLayout = QtWidgets.QVBoxLayout()
        self.rightLayout.setObjectName("rightLayout")
        self.player1Group = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.player1Group.setObjectName("player1Group")
        self.player1Layout = QtWidgets.QVBoxLayout(self.player1Group)
        self.player1Layout.setObjectName("player1Layout")
        self.player1Name = QtWidgets.QLineEdit(parent=self.player1Group)
        self.player1Name.setStyleSheet("\n"
"                padding: 5px;\n"
"                font-size: 14px;\n"
"                background: #f8f8f8;\n"
"                border: 1px solid #ddd;\n"
"                color: #333;\n"
"               ")
        self.player1Name.setReadOnly(True)
        self.player1Name.setObjectName("player1Name")
        self.player1Layout.addWidget(self.player1Name)
        self.player1listView = QtWidgets.QListView(parent=self.player1Group)
        self.player1listView.setStyleSheet("\n"
"                QListView {\n"
"                 background: #f8f8f8;\n"
"                 border: 1px solid #ddd;\n"
"                 border-radius: 5px;\n"
"                 padding: 5px;\n"
"                }\n"
"               ")
        self.player1listView.setObjectName("player1listView")
        self.player1Layout.addWidget(self.player1listView)
        self.rightLayout.addWidget(self.player1Group)
        self.player2Group = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.player2Group.setObjectName("player2Group")
        self.player2Layout = QtWidgets.QVBoxLayout(self.player2Group)
        self.player2Layout.setObjectName("player2Layout")
        self.player2Name = QtWidgets.QLineEdit(parent=self.player2Group)
        self.player2Name.setStyleSheet("\n"
"                padding: 5px;\n"
"                font-size: 14px;\n"
"                background: #f8f8f8;\n"
"                border: 1px solid #ddd;\n"
"                color: #333;\n"
"               ")
        self.player2Name.setReadOnly(True)
        self.player2Name.setObjectName("player2Name")
        self.player2Layout.addWidget(self.player2Name)
        self.player2listView = QtWidgets.QListView(parent=self.player2Group)
        self.player2listView.setStyleSheet("\n"
"                QListView {\n"
"                 background: #f8f8f8;\n"
"                 border: 1px solid #ddd;\n"
"                 border-radius: 5px;\n"
"                 padding: 5px;\n"
"                }\n"
"               ")
        self.player2listView.setObjectName("player2listView")
        self.player2Layout.addWidget(self.player2listView)
        self.rightLayout.addWidget(self.player2Group)
        self.endButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.endButton.setStyleSheet("\n"
"             QPushButton {\n"
"              background: #d9534f;\n"
"              color: white;\n"
"              border: none;\n"
"              padding: 8px 16px;\n"
"              border-radius: 4px;\n"
"              font-weight: bold;\n"
"             }\n"
"             QPushButton:hover {\n"
"              background: #c9302c;\n"
"             }\n"
"            ")
        self.endButton.setObjectName("endButton")
        self.rightLayout.addWidget(self.endButton)
        self.mainLayout.addLayout(self.rightLayout)
        self.outerVerticalLayout.addLayout(self.mainLayout)
        ChessGameWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ChessGameWindow)
        QtCore.QMetaObject.connectSlotsByName(ChessGameWindow)

    def retranslateUi(self, ChessGameWindow):
        _translate = QtCore.QCoreApplication.translate
        ChessGameWindow.setWindowTitle(_translate("ChessGameWindow", "Chess Game"))
        self.gameInfoGroup.setTitle(_translate("ChessGameWindow", "Game Information"))
        self.gameNameLabel.setText(_translate("ChessGameWindow", "Game: "))
        self.roundLabel.setText(_translate("ChessGameWindow", "Round: "))
        self.siteLabel.setText(_translate("ChessGameWindow", "Site: "))
        self.chessboardStatusIndicator.setToolTip(_translate("ChessGameWindow", "Chessboard Connection"))
        self.gameStatusIndicator.setToolTip(_translate("ChessGameWindow", "Game Status"))
        self.player1Group.setTitle(_translate("ChessGameWindow", "White Player"))
        self.player2Group.setTitle(_translate("ChessGameWindow", "Black Player"))
        self.endButton.setText(_translate("ChessGameWindow", "End Game"))
