# Form implementation generated from reading ui file 'ui/newGame.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_newGame(object):
    def setupUi(self, newGame):
        newGame.setObjectName("newGame")
        newGame.resize(450, 300)
        newGame.setMinimumSize(QtCore.QSize(400, 250))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\../img/app.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        newGame.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(newGame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=newGame)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.gameNameEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.gameNameEdit.setObjectName("gameNameEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.gameNameEdit)
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.whitePlayerEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.whitePlayerEdit.setObjectName("whitePlayerEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.whitePlayerEdit)
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.blackPlayerEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.blackPlayerEdit.setObjectName("blackPlayerEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.blackPlayerEdit)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.proceedButton = QtWidgets.QPushButton(parent=newGame)
        self.proceedButton.setMinimumSize(QtCore.QSize(100, 30))
        self.proceedButton.setObjectName("proceedButton")
        self.horizontalLayout.addWidget(self.proceedButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(newGame)
        QtCore.QMetaObject.connectSlotsByName(newGame)

    def retranslateUi(self, newGame):
        _translate = QtCore.QCoreApplication.translate
        newGame.setWindowTitle(_translate("newGame", "New Chess Game"))
        self.groupBox.setTitle(_translate("newGame", "Game Information"))
        self.label.setText(_translate("newGame", "Game Name:"))
        self.gameNameEdit.setPlaceholderText(_translate("newGame", "Enter game name"))
        self.label_2.setText(_translate("newGame", "White Player:"))
        self.whitePlayerEdit.setPlaceholderText(_translate("newGame", "Enter white player name"))
        self.label_3.setText(_translate("newGame", "Black Player:"))
        self.blackPlayerEdit.setPlaceholderText(_translate("newGame", "Enter black player name"))
        self.proceedButton.setText(_translate("newGame", "Proceed"))
