# Form implementation generated from reading ui file 'ui\Chess Game.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1293, 845)
        MainWindow.setAcceptDrops(True)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(130, 90, 761, 641))
        self.widget.setMouseTracking(True)
        self.widget.setAcceptDrops(True)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.L_15 = QtWidgets.QLabel(parent=self.widget)
        self.L_15.setMouseTracking(True)
        self.L_15.setAcceptDrops(True)
        self.L_15.setAutoFillBackground(False)
        self.L_15.setStyleSheet("QLabel {\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"")
        self.L_15.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_15.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_15.setLineWidth(0)
        self.L_15.setText("")
        self.L_15.setPixmap(QtGui.QPixmap("ui\\Black-Pawn.png"))
        self.L_15.setScaledContents(False)
        self.L_15.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_15.setWordWrap(True)
        self.L_15.setIndent(0)
        self.L_15.setObjectName("L_15")
        self.gridLayout.addWidget(self.L_15, 7, 1, 1, 1)
        self.L_64 = QtWidgets.QLabel(parent=self.widget)
        self.L_64.setMouseTracking(True)
        self.L_64.setAcceptDrops(True)
        self.L_64.setStyleSheet("QLabel {\n"
"    background-color: rgb(246, 255, 233);\n"
"}\n"
"")
        self.L_64.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_64.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_64.setLineWidth(0)
        self.L_64.setText("")
        self.L_64.setPixmap(QtGui.QPixmap("ui\\White-Rook.png"))
        self.L_64.setScaledContents(False)
        self.L_64.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_64.setWordWrap(True)
        self.L_64.setIndent(0)
        self.L_64.setObjectName("L_64")
        self.gridLayout.addWidget(self.L_64, 0, 0, 1, 1)
        self.L_42 = QtWidgets.QLabel(parent=self.widget)
        self.L_42.setMouseTracking(True)
        self.L_42.setAcceptDrops(True)
        self.L_42.setStyleSheet("QLabel {\n"
"    background-color: rgb(246, 255, 233);\n"
"}\n"
"")
        self.L_42.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_42.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_42.setLineWidth(0)
        self.L_42.setText("")
        self.L_42.setScaledContents(False)
        self.L_42.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_42.setWordWrap(True)
        self.L_42.setIndent(0)
        self.L_42.setObjectName("L_42")
        self.gridLayout.addWidget(self.L_42, 2, 6, 1, 1)
        self.L_9 = QtWidgets.QLabel(parent=self.widget)
        self.L_9.setEnabled(True)
        self.L_9.setMouseTracking(True)
        self.L_9.setAcceptDrops(True)
        self.L_9.setAutoFillBackground(False)
        self.L_9.setStyleSheet("QLabel {\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"")
        self.L_9.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_9.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_9.setLineWidth(0)
        self.L_9.setText("")
        self.L_9.setPixmap(QtGui.QPixmap("ui\\Black-Pawn.png"))
        self.L_9.setScaledContents(False)
        self.L_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_9.setWordWrap(True)
        self.L_9.setIndent(0)
        self.L_9.setObjectName("L_9")
        self.gridLayout.addWidget(self.L_9, 7, 7, 1, 1)
        self.L_25 = QtWidgets.QLabel(parent=self.widget)
        self.L_25.setMouseTracking(True)
        self.L_25.setAcceptDrops(True)
        self.L_25.setStyleSheet("QLabel {\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"")
        self.L_25.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_25.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_25.setLineWidth(0)
        self.L_25.setText("")
        self.L_25.setScaledContents(False)
        self.L_25.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_25.setWordWrap(True)
        self.L_25.setIndent(0)
        self.L_25.setObjectName("L_25")
        self.gridLayout.addWidget(self.L_25, 4, 7, 1, 1)
        self.L_16 = QtWidgets.QLabel(parent=self.widget)
        self.L_16.setMouseTracking(True)
        self.L_16.setAcceptDrops(True)
        self.L_16.setStyleSheet("QLabel {\n"
"    background-color: rgb(246, 255, 233);\n"
"}\n"
"")
        self.L_16.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_16.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_16.setLineWidth(0)
        self.L_16.setText("")
        self.L_16.setPixmap(QtGui.QPixmap("ui\\Black-Pawn.png"))
        self.L_16.setScaledContents(False)
        self.L_16.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_16.setWordWrap(True)
        self.L_16.setIndent(0)
        self.L_16.setObjectName("L_16")
        self.gridLayout.addWidget(self.L_16, 7, 0, 1, 1)
        self.L_11 = QtWidgets.QLabel(parent=self.widget)
        self.L_11.setMouseTracking(True)
        self.L_11.setAcceptDrops(True)
        self.L_11.setStyleSheet("QLabel {\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"")
        self.L_11.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_11.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_11.setLineWidth(0)
        self.L_11.setText("")
        self.L_11.setPixmap(QtGui.QPixmap("ui\\Black-Pawn.png"))
        self.L_11.setScaledContents(False)
        self.L_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_11.setWordWrap(True)
        self.L_11.setIndent(0)
        self.L_11.setObjectName("L_11")
        self.gridLayout.addWidget(self.L_11, 7, 5, 1, 1)
        self.L_61 = QtWidgets.QLabel(parent=self.widget)
        self.L_61.setMouseTracking(True)
        self.L_61.setAcceptDrops(True)
        self.L_61.setStyleSheet("QLabel {\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"")
        self.L_61.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_61.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_61.setLineWidth(0)
        self.L_61.setText("")
        self.L_61.setPixmap(QtGui.QPixmap("ui\\White-King.png"))
        self.L_61.setScaledContents(False)
        self.L_61.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_61.setWordWrap(True)
        self.L_61.setIndent(0)
        self.L_61.setObjectName("L_61")
        self.gridLayout.addWidget(self.L_61, 0, 3, 1, 1)
        self.L_50 = QtWidgets.QLabel(parent=self.widget)
        self.L_50.setMouseTracking(True)
        self.L_50.setAcceptDrops(True)
        self.L_50.setStyleSheet("QLabel {\n"
"    background-color: rgb(246, 255, 233);\n"
"}\n"
"")
        self.L_50.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_50.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_50.setLineWidth(0)
        self.L_50.setText("")
        self.L_50.setPixmap(QtGui.QPixmap("ui\\White-Pawn.png"))
        self.L_50.setScaledContents(False)
        self.L_50.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_50.setWordWrap(True)
        self.L_50.setIndent(0)
        self.L_50.setObjectName("L_50")
        self.gridLayout.addWidget(self.L_50, 1, 1, 1, 1)
        self.L_24 = QtWidgets.QLabel(parent=self.widget)
        self.L_24.setMouseTracking(True)
        self.L_24.setAcceptDrops(True)
        self.L_24.setStyleSheet("QLabel {\n"
"    background-color: rgb(246, 255, 233);\n"
"}\n"
"")
        self.L_24.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_24.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_24.setLineWidth(0)
        self.L_24.setText("")
        self.L_24.setScaledContents(False)
        self.L_24.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_24.setWordWrap(True)
        self.L_24.setIndent(0)
        self.L_24.setObjectName("L_24")
        self.gridLayout.addWidget(self.L_24, 5, 7, 1, 1)
        self.L_29 = QtWidgets.QLabel(parent=self.widget)
        self.L_29.setMouseTracking(True)
        self.L_29.setAcceptDrops(True)
        self.L_29.setStyleSheet("QLabel {\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"")
        self.L_29.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_29.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_29.setLineWidth(0)
        self.L_29.setText("")
        self.L_29.setScaledContents(False)
        self.L_29.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_29.setWordWrap(True)
        self.L_29.setIndent(0)
        self.L_29.setObjectName("L_29")
        self.gridLayout.addWidget(self.L_29, 4, 3, 1, 1)
        self.L_53 = QtWidgets.QLabel(parent=self.widget)
        self.L_53.setMouseTracking(True)
        self.L_53.setAcceptDrops(True)
        self.L_53.setStyleSheet("QLabel {\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"")
        self.L_53.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_53.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_53.setLineWidth(0)
        self.L_53.setText("")
        self.L_53.setPixmap(QtGui.QPixmap("ui\\White-Pawn.png"))
        self.L_53.setScaledContents(False)
        self.L_53.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_53.setWordWrap(True)
        self.L_53.setIndent(0)
        self.L_53.setObjectName("L_53")
        self.gridLayout.addWidget(self.L_53, 1, 4, 1, 1)
        self.L_12 = QtWidgets.QLabel(parent=self.widget)
        self.L_12.setMouseTracking(True)
        self.L_12.setAcceptDrops(True)
        self.L_12.setStyleSheet("QLabel {\n"
"    background-color: rgb(246, 255, 233);\n"
"}\n"
"")
        self.L_12.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_12.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_12.setLineWidth(0)
        self.L_12.setText("")
        self.L_12.setPixmap(QtGui.QPixmap("ui\\Black-Pawn.png"))
        self.L_12.setScaledContents(False)
        self.L_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_12.setWordWrap(True)
        self.L_12.setIndent(0)
        self.L_12.setObjectName("L_12")
        self.gridLayout.addWidget(self.L_12, 7, 4, 1, 1)
        self.L_14 = QtWidgets.QLabel(parent=self.widget)
        self.L_14.setMouseTracking(True)
        self.L_14.setAcceptDrops(True)
        self.L_14.setStyleSheet("QLabel {\n"
"    background-color: rgb(246, 255, 233);\n"
"}\n"
"")
        self.L_14.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_14.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_14.setLineWidth(0)
        self.L_14.setText("")
        self.L_14.setPixmap(QtGui.QPixmap("ui\\Black-Pawn.png"))
        self.L_14.setScaledContents(False)
        self.L_14.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_14.setWordWrap(True)
        self.L_14.setIndent(0)
        self.L_14.setObjectName("L_14")
        self.gridLayout.addWidget(self.L_14, 7, 2, 1, 1)
        self.L_59 = QtWidgets.QLabel(parent=self.widget)
        self.L_59.setMouseTracking(True)
        self.L_59.setAcceptDrops(True)
        self.L_59.setStyleSheet("QLabel {\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"")
        self.L_59.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_59.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_59.setLineWidth(0)
        self.L_59.setText("")
        self.L_59.setPixmap(QtGui.QPixmap("ui\\White-Bishop.png"))
        self.L_59.setScaledContents(False)
        self.L_59.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_59.setWordWrap(True)
        self.L_59.setIndent(0)
        self.L_59.setObjectName("L_59")
        self.gridLayout.addWidget(self.L_59, 0, 5, 1, 1)
        self.L_4 = QtWidgets.QLabel(parent=self.widget)
        self.L_4.setMouseTracking(True)
        self.L_4.setAcceptDrops(True)
        self.L_4.setStyleSheet("QLabel {\n"
"    background-color: rgb(246, 255, 233);\n"
"}\n"
"")
        self.L_4.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_4.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_4.setLineWidth(0)
        self.L_4.setText("")
        self.L_4.setPixmap(QtGui.QPixmap("ui\\Black-King.png"))
        self.L_4.setScaledContents(False)
        self.L_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_4.setWordWrap(True)
        self.L_4.setIndent(0)
        self.L_4.setObjectName("L_4")
        self.gridLayout.addWidget(self.L_4, 14, 3, 1, 1)
        self.L_32 = QtWidgets.QLabel(parent=self.widget)
        self.L_32.setMouseTracking(True)
        self.L_32.setAcceptDrops(True)
        self.L_32.setStyleSheet("QLabel {\n"
"    background-color: rgb(246, 255, 233);\n"
"}\n"
"")
        self.L_32.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_32.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_32.setLineWidth(0)
        self.L_32.setText("")
        self.L_32.setScaledContents(False)
        self.L_32.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_32.setWordWrap(True)
        self.L_32.setIndent(0)
        self.L_32.setObjectName("L_32")
        self.gridLayout.addWidget(self.L_32, 4, 0, 1, 1)
        self.L_40 = QtWidgets.QLabel(parent=self.widget)
        self.L_40.setMouseTracking(True)
        self.L_40.setAcceptDrops(True)
        self.L_40.setStyleSheet("QLabel {\n"
"    background-color: rgb(246, 255, 233);\n"
"}\n"
"")
        self.L_40.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_40.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_40.setLineWidth(0)
        self.L_40.setText("")
        self.L_40.setScaledContents(False)
        self.L_40.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_40.setWordWrap(True)
        self.L_40.setIndent(0)
        self.L_40.setObjectName("L_40")
        self.gridLayout.addWidget(self.L_40, 3, 7, 1, 1)
        self.L_22 = QtWidgets.QLabel(parent=self.widget)
        self.L_22.setMouseTracking(True)
        self.L_22.setAcceptDrops(True)
        self.L_22.setStyleSheet("QLabel {\n"
"    background-color: rgb(246, 255, 233);\n"
"}\n"
"")
        self.L_22.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_22.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_22.setLineWidth(0)
        self.L_22.setText("")
        self.L_22.setScaledContents(False)
        self.L_22.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_22.setWordWrap(True)
        self.L_22.setIndent(0)
        self.L_22.setObjectName("L_22")
        self.gridLayout.addWidget(self.L_22, 5, 5, 1, 1)
        self.L_54 = QtWidgets.QLabel(parent=self.widget)
        self.L_54.setMouseTracking(True)
        self.L_54.setAcceptDrops(True)
        self.L_54.setStyleSheet("QLabel {\n"
"    background-color: rgb(246, 255, 233);\n"
"}\n"
"")
        self.L_54.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_54.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_54.setLineWidth(0)
        self.L_54.setText("")
        self.L_54.setPixmap(QtGui.QPixmap("ui\\White-Pawn.png"))
        self.L_54.setScaledContents(False)
        self.L_54.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_54.setWordWrap(True)
        self.L_54.setIndent(0)
        self.L_54.setObjectName("L_54")
        self.gridLayout.addWidget(self.L_54, 1, 5, 1, 1)
        self.L_35 = QtWidgets.QLabel(parent=self.widget)
        self.L_35.setMouseTracking(True)
        self.L_35.setAcceptDrops(True)
        self.L_35.setStyleSheet("QLabel {\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"")
        self.L_35.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_35.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_35.setLineWidth(0)
        self.L_35.setText("")
        self.L_35.setScaledContents(False)
        self.L_35.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_35.setWordWrap(True)
        self.L_35.setIndent(0)
        self.L_35.setObjectName("L_35")
        self.gridLayout.addWidget(self.L_35, 3, 2, 1, 1)
        self.L_20 = QtWidgets.QLabel(parent=self.widget)
        self.L_20.setMouseTracking(True)
        self.L_20.setAcceptDrops(True)
        self.L_20.setStyleSheet("QLabel {\n"
"    background-color: rgb(246, 255, 233);\n"
"}\n"
"")
        self.L_20.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_20.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_20.setLineWidth(0)
        self.L_20.setText("")
        self.L_20.setScaledContents(False)
        self.L_20.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_20.setWordWrap(True)
        self.L_20.setIndent(0)
        self.L_20.setObjectName("L_20")
        self.gridLayout.addWidget(self.L_20, 5, 3, 1, 1)
        self.L_10 = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.L_10.setFont(font)
        self.L_10.setMouseTracking(True)
        self.L_10.setAcceptDrops(True)
        self.L_10.setAutoFillBackground(False)
        self.L_10.setStyleSheet("QLabel {\n"
"    background-color: rgb(246, 255, 233);\n"
"}\n"
"")
        self.L_10.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_10.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_10.setLineWidth(0)
        self.L_10.setText("")
        self.L_10.setPixmap(QtGui.QPixmap("ui\\Black-Pawn.png"))
        self.L_10.setScaledContents(False)
        self.L_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_10.setWordWrap(True)
        self.L_10.setIndent(0)
        self.L_10.setObjectName("L_10")
        self.gridLayout.addWidget(self.L_10, 7, 6, 1, 1)
        self.L_39 = QtWidgets.QLabel(parent=self.widget)
        self.L_39.setMouseTracking(True)
        self.L_39.setAcceptDrops(True)
        self.L_39.setStyleSheet("QLabel {\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"")
        self.L_39.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_39.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_39.setLineWidth(0)
        self.L_39.setText("")
        self.L_39.setScaledContents(False)
        self.L_39.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_39.setWordWrap(True)
        self.L_39.setIndent(0)
        self.L_39.setObjectName("L_39")
        self.gridLayout.addWidget(self.L_39, 3, 6, 1, 1)
        self.L_43 = QtWidgets.QLabel(parent=self.widget)
        self.L_43.setMouseTracking(True)
        self.L_43.setAcceptDrops(True)
        self.L_43.setStyleSheet("QLabel {\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"")
        self.L_43.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_43.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_43.setLineWidth(0)
        self.L_43.setText("")
        self.L_43.setScaledContents(False)
        self.L_43.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_43.setWordWrap(True)
        self.L_43.setIndent(0)
        self.L_43.setObjectName("L_43")
        self.gridLayout.addWidget(self.L_43, 2, 5, 1, 1)
        self.L_49 = QtWidgets.QLabel(parent=self.widget)
        self.L_49.setMouseTracking(True)
        self.L_49.setAcceptDrops(True)
        self.L_49.setStyleSheet("QLabel {\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"")
        self.L_49.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_49.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_49.setLineWidth(0)
        self.L_49.setText("")
        self.L_49.setPixmap(QtGui.QPixmap("ui\\White-Pawn.png"))
        self.L_49.setScaledContents(False)
        self.L_49.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_49.setWordWrap(True)
        self.L_49.setIndent(0)
        self.L_49.setObjectName("L_49")
        self.gridLayout.addWidget(self.L_49, 1, 0, 1, 1)
        self.L_63 = QtWidgets.QLabel(parent=self.widget)
        self.L_63.setMouseTracking(True)
        self.L_63.setAcceptDrops(True)
        self.L_63.setStyleSheet("QLabel {\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"")
        self.L_63.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_63.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_63.setLineWidth(0)
        self.L_63.setText("")
        self.L_63.setPixmap(QtGui.QPixmap("ui\\White-Knight.png"))
        self.L_63.setScaledContents(False)
        self.L_63.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_63.setWordWrap(True)
        self.L_63.setIndent(0)
        self.L_63.setObjectName("L_63")
        self.gridLayout.addWidget(self.L_63, 0, 1, 1, 1)
        self.L_60 = QtWidgets.QLabel(parent=self.widget)
        self.L_60.setMouseTracking(True)
        self.L_60.setAcceptDrops(True)
        self.L_60.setStyleSheet("QLabel {\n"
"    background-color: rgb(246, 255, 233);\n"
"}\n"
"")
        self.L_60.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_60.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_60.setLineWidth(0)
        self.L_60.setText("")
        self.L_60.setPixmap(QtGui.QPixmap("ui\\White-Queen.png"))
        self.L_60.setScaledContents(False)
        self.L_60.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_60.setWordWrap(True)
        self.L_60.setIndent(0)
        self.L_60.setObjectName("L_60")
        self.gridLayout.addWidget(self.L_60, 0, 4, 1, 1)
        self.L_26 = QtWidgets.QLabel(parent=self.widget)
        self.L_26.setMouseTracking(True)
        self.L_26.setAcceptDrops(True)
        self.L_26.setStyleSheet("QLabel {\n"
"    background-color: rgb(246, 255, 233);\n"
"}\n"
"")
        self.L_26.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_26.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_26.setLineWidth(0)
        self.L_26.setText("")
        self.L_26.setScaledContents(False)
        self.L_26.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_26.setWordWrap(True)
        self.L_26.setIndent(0)
        self.L_26.setObjectName("L_26")
        self.gridLayout.addWidget(self.L_26, 4, 6, 1, 1)
        self.L_8 = QtWidgets.QLabel(parent=self.widget)
        self.L_8.setMouseTracking(True)
        self.L_8.setAcceptDrops(True)
        self.L_8.setAutoFillBackground(False)
        self.L_8.setStyleSheet("QLabel {\n"
"    background-color: rgb(246, 255, 233);\n"
"}\n"
"")
        self.L_8.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_8.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_8.setLineWidth(0)
        self.L_8.setText("")
        self.L_8.setPixmap(QtGui.QPixmap("ui\\Black-Rook.png"))
        self.L_8.setScaledContents(False)
        self.L_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_8.setWordWrap(True)
        self.L_8.setIndent(0)
        self.L_8.setObjectName("L_8")
        self.gridLayout.addWidget(self.L_8, 14, 7, 1, 1)
        self.L_57 = QtWidgets.QLabel(parent=self.widget)
        self.L_57.setMouseTracking(True)
        self.L_57.setAcceptDrops(True)
        self.L_57.setStyleSheet("QLabel {\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"")
        self.L_57.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_57.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_57.setLineWidth(0)
        self.L_57.setText("")
        self.L_57.setPixmap(QtGui.QPixmap("ui\\White-Rook.png"))
        self.L_57.setScaledContents(False)
        self.L_57.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_57.setWordWrap(True)
        self.L_57.setIndent(0)
        self.L_57.setObjectName("L_57")
        self.gridLayout.addWidget(self.L_57, 0, 7, 1, 1)
        self.L_36 = QtWidgets.QLabel(parent=self.widget)
        self.L_36.setMouseTracking(True)
        self.L_36.setAcceptDrops(True)
        self.L_36.setStyleSheet("QLabel {\n"
"    background-color: rgb(246, 255, 233);\n"
"}\n"
"")
        self.L_36.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_36.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_36.setLineWidth(0)
        self.L_36.setText("")
        self.L_36.setScaledContents(False)
        self.L_36.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_36.setWordWrap(True)
        self.L_36.setIndent(0)
        self.L_36.setObjectName("L_36")
        self.gridLayout.addWidget(self.L_36, 3, 3, 1, 1)
        self.L_1 = QtWidgets.QLabel(parent=self.widget)
        self.L_1.setMouseTracking(True)
        self.L_1.setAcceptDrops(True)
        self.L_1.setStyleSheet("QLabel {\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"")
        self.L_1.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_1.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_1.setLineWidth(0)
        self.L_1.setText("")
        self.L_1.setPixmap(QtGui.QPixmap("ui\\Black-Rook.png"))
        self.L_1.setScaledContents(False)
        self.L_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_1.setWordWrap(True)
        self.L_1.setIndent(0)
        self.L_1.setObjectName("L_1")
        self.gridLayout.addWidget(self.L_1, 14, 0, 1, 1)
        self.L_51 = QtWidgets.QLabel(parent=self.widget)
        self.L_51.setMouseTracking(True)
        self.L_51.setAcceptDrops(True)
        self.L_51.setStyleSheet("QLabel {\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"")
        self.L_51.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_51.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_51.setLineWidth(0)
        self.L_51.setText("")
        self.L_51.setPixmap(QtGui.QPixmap("ui\\White-Pawn.png"))
        self.L_51.setScaledContents(False)
        self.L_51.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_51.setWordWrap(True)
        self.L_51.setIndent(0)
        self.L_51.setObjectName("L_51")
        self.gridLayout.addWidget(self.L_51, 1, 2, 1, 1)
        self.L_27 = QtWidgets.QLabel(parent=self.widget)
        self.L_27.setMouseTracking(True)
        self.L_27.setAcceptDrops(True)
        self.L_27.setStyleSheet("QLabel {\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"")
        self.L_27.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_27.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_27.setLineWidth(0)
        self.L_27.setText("")
        self.L_27.setScaledContents(False)
        self.L_27.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_27.setWordWrap(True)
        self.L_27.setIndent(0)
        self.L_27.setObjectName("L_27")
        self.gridLayout.addWidget(self.L_27, 4, 5, 1, 1)
        self.L_33 = QtWidgets.QLabel(parent=self.widget)
        self.L_33.setMouseTracking(True)
        self.L_33.setAcceptDrops(True)
        self.L_33.setStyleSheet("QLabel {\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"")
        self.L_33.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_33.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_33.setLineWidth(0)
        self.L_33.setText("")
        self.L_33.setScaledContents(False)
        self.L_33.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_33.setWordWrap(True)
        self.L_33.setIndent(0)
        self.L_33.setObjectName("L_33")
        self.gridLayout.addWidget(self.L_33, 3, 0, 1, 1)
        self.L_18 = QtWidgets.QLabel(parent=self.widget)
        self.L_18.setMouseTracking(True)
        self.L_18.setAcceptDrops(True)
        self.L_18.setStyleSheet("QLabel {\n"
"    background-color: rgb(246, 255, 233);\n"
"}\n"
"")
        self.L_18.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_18.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_18.setLineWidth(0)
        self.L_18.setText("")
        self.L_18.setScaledContents(False)
        self.L_18.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_18.setWordWrap(True)
        self.L_18.setIndent(0)
        self.L_18.setObjectName("L_18")
        self.gridLayout.addWidget(self.L_18, 5, 1, 1, 1)
        self.L_37 = QtWidgets.QLabel(parent=self.widget)
        self.L_37.setMouseTracking(True)
        self.L_37.setAcceptDrops(True)
        self.L_37.setStyleSheet("QLabel {\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"")
        self.L_37.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_37.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_37.setLineWidth(0)
        self.L_37.setText("")
        self.L_37.setScaledContents(False)
        self.L_37.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_37.setWordWrap(True)
        self.L_37.setIndent(0)
        self.L_37.setObjectName("L_37")
        self.gridLayout.addWidget(self.L_37, 3, 4, 1, 1)
        self.L_23 = QtWidgets.QLabel(parent=self.widget)
        self.L_23.setMouseTracking(True)
        self.L_23.setAcceptDrops(True)
        self.L_23.setStyleSheet("QLabel {\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"")
        self.L_23.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_23.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_23.setLineWidth(0)
        self.L_23.setText("")
        self.L_23.setScaledContents(False)
        self.L_23.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_23.setWordWrap(True)
        self.L_23.setIndent(0)
        self.L_23.setObjectName("L_23")
        self.gridLayout.addWidget(self.L_23, 5, 6, 1, 1)
        self.L_62 = QtWidgets.QLabel(parent=self.widget)
        self.L_62.setMouseTracking(True)
        self.L_62.setAcceptDrops(True)
        self.L_62.setStyleSheet("QLabel {\n"
"    background-color: rgb(246, 255, 233);\n"
"}\n"
"")
        self.L_62.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_62.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_62.setLineWidth(0)
        self.L_62.setText("")
        self.L_62.setPixmap(QtGui.QPixmap("ui\\White-Bishop.png"))
        self.L_62.setScaledContents(False)
        self.L_62.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_62.setWordWrap(True)
        self.L_62.setIndent(0)
        self.L_62.setObjectName("L_62")
        self.gridLayout.addWidget(self.L_62, 0, 2, 1, 1)
        self.L_46 = QtWidgets.QLabel(parent=self.widget)
        self.L_46.setMouseTracking(True)
        self.L_46.setAcceptDrops(True)
        self.L_46.setStyleSheet("QLabel {\n"
"    background-color: rgb(246, 255, 233);\n"
"}\n"
"")
        self.L_46.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_46.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_46.setLineWidth(0)
        self.L_46.setText("")
        self.L_46.setScaledContents(False)
        self.L_46.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_46.setWordWrap(True)
        self.L_46.setIndent(0)
        self.L_46.setObjectName("L_46")
        self.gridLayout.addWidget(self.L_46, 2, 2, 1, 1)
        self.L_2 = QtWidgets.QLabel(parent=self.widget)
        self.L_2.setMouseTracking(True)
        self.L_2.setAcceptDrops(True)
        self.L_2.setStyleSheet("QLabel {\n"
"    background-color: rgb(246, 255, 233);\n"
"}\n"
"")
        self.L_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_2.setLineWidth(0)
        self.L_2.setText("")
        self.L_2.setPixmap(QtGui.QPixmap("ui\\Black-Knight.png"))
        self.L_2.setScaledContents(False)
        self.L_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_2.setWordWrap(True)
        self.L_2.setIndent(0)
        self.L_2.setObjectName("L_2")
        self.gridLayout.addWidget(self.L_2, 14, 1, 1, 1)
        self.L_30 = QtWidgets.QLabel(parent=self.widget)
        self.L_30.setMouseTracking(True)
        self.L_30.setAcceptDrops(True)
        self.L_30.setStyleSheet("QLabel {\n"
"    background-color: rgb(246, 255, 233);\n"
"}\n"
"")
        self.L_30.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_30.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_30.setLineWidth(0)
        self.L_30.setText("")
        self.L_30.setScaledContents(False)
        self.L_30.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_30.setWordWrap(True)
        self.L_30.setIndent(0)
        self.L_30.setObjectName("L_30")
        self.gridLayout.addWidget(self.L_30, 4, 2, 1, 1)
        self.L_5 = QtWidgets.QLabel(parent=self.widget)
        self.L_5.setMouseTracking(True)
        self.L_5.setAcceptDrops(True)
        self.L_5.setStyleSheet("QLabel {\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"")
        self.L_5.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_5.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_5.setLineWidth(0)
        self.L_5.setText("")
        self.L_5.setPixmap(QtGui.QPixmap("ui\\Black-Queen.png"))
        self.L_5.setScaledContents(False)
        self.L_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_5.setWordWrap(True)
        self.L_5.setIndent(0)
        self.L_5.setObjectName("L_5")
        self.gridLayout.addWidget(self.L_5, 14, 4, 1, 1)
        self.L_34 = QtWidgets.QLabel(parent=self.widget)
        self.L_34.setMouseTracking(True)
        self.L_34.setAcceptDrops(True)
        self.L_34.setStyleSheet("QLabel {\n"
"    background-color: rgb(246, 255, 233);\n"
"}\n"
"")
        self.L_34.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_34.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_34.setLineWidth(0)
        self.L_34.setText("")
        self.L_34.setScaledContents(False)
        self.L_34.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_34.setWordWrap(True)
        self.L_34.setIndent(0)
        self.L_34.setObjectName("L_34")
        self.gridLayout.addWidget(self.L_34, 3, 1, 1, 1)
        self.L_41 = QtWidgets.QLabel(parent=self.widget)
        self.L_41.setMouseTracking(True)
        self.L_41.setAcceptDrops(True)
        self.L_41.setStyleSheet("QLabel {\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"")
        self.L_41.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_41.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_41.setLineWidth(0)
        self.L_41.setText("")
        self.L_41.setScaledContents(False)
        self.L_41.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_41.setWordWrap(True)
        self.L_41.setIndent(0)
        self.L_41.setObjectName("L_41")
        self.gridLayout.addWidget(self.L_41, 2, 7, 1, 1)
        self.L_52 = QtWidgets.QLabel(parent=self.widget)
        self.L_52.setMouseTracking(True)
        self.L_52.setAcceptDrops(True)
        self.L_52.setStyleSheet("QLabel {\n"
"    background-color: rgb(246, 255, 233);\n"
"}\n"
"")
        self.L_52.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_52.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_52.setLineWidth(0)
        self.L_52.setText("")
        self.L_52.setPixmap(QtGui.QPixmap("ui\\White-Pawn.png"))
        self.L_52.setScaledContents(False)
        self.L_52.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_52.setWordWrap(True)
        self.L_52.setIndent(0)
        self.L_52.setObjectName("L_52")
        self.gridLayout.addWidget(self.L_52, 1, 3, 1, 1)
        self.L_38 = QtWidgets.QLabel(parent=self.widget)
        self.L_38.setMouseTracking(True)
        self.L_38.setAcceptDrops(True)
        self.L_38.setStyleSheet("QLabel {\n"
"    background-color: rgb(246, 255, 233);\n"
"}\n"
"")
        self.L_38.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_38.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_38.setLineWidth(0)
        self.L_38.setText("")
        self.L_38.setScaledContents(False)
        self.L_38.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_38.setWordWrap(True)
        self.L_38.setIndent(0)
        self.L_38.setObjectName("L_38")
        self.gridLayout.addWidget(self.L_38, 3, 5, 1, 1)
        self.L_55 = QtWidgets.QLabel(parent=self.widget)
        self.L_55.setMouseTracking(True)
        self.L_55.setAcceptDrops(True)
        self.L_55.setStyleSheet("QLabel {\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"")
        self.L_55.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_55.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_55.setLineWidth(0)
        self.L_55.setText("")
        self.L_55.setPixmap(QtGui.QPixmap("ui\\White-Pawn.png"))
        self.L_55.setScaledContents(False)
        self.L_55.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_55.setWordWrap(True)
        self.L_55.setIndent(0)
        self.L_55.setObjectName("L_55")
        self.gridLayout.addWidget(self.L_55, 1, 6, 1, 1)
        self.L_31 = QtWidgets.QLabel(parent=self.widget)
        self.L_31.setMouseTracking(True)
        self.L_31.setAcceptDrops(True)
        self.L_31.setStyleSheet("QLabel {\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"")
        self.L_31.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_31.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_31.setLineWidth(0)
        self.L_31.setText("")
        self.L_31.setScaledContents(False)
        self.L_31.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_31.setWordWrap(True)
        self.L_31.setIndent(0)
        self.L_31.setObjectName("L_31")
        self.gridLayout.addWidget(self.L_31, 4, 1, 1, 1)
        self.L_17 = QtWidgets.QLabel(parent=self.widget)
        self.L_17.setMouseTracking(True)
        self.L_17.setAcceptDrops(True)
        self.L_17.setStyleSheet("QLabel {\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"")
        self.L_17.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_17.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_17.setLineWidth(0)
        self.L_17.setText("")
        self.L_17.setScaledContents(False)
        self.L_17.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_17.setWordWrap(True)
        self.L_17.setIndent(0)
        self.L_17.setObjectName("L_17")
        self.gridLayout.addWidget(self.L_17, 5, 0, 1, 1)
        self.L_28 = QtWidgets.QLabel(parent=self.widget)
        self.L_28.setMouseTracking(True)
        self.L_28.setAcceptDrops(True)
        self.L_28.setStyleSheet("QLabel {\n"
"    background-color: rgb(246, 255, 233);\n"
"}\n"
"")
        self.L_28.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_28.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_28.setLineWidth(0)
        self.L_28.setText("")
        self.L_28.setScaledContents(False)
        self.L_28.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_28.setWordWrap(True)
        self.L_28.setIndent(0)
        self.L_28.setObjectName("L_28")
        self.gridLayout.addWidget(self.L_28, 4, 4, 1, 1)
        self.L_21 = QtWidgets.QLabel(parent=self.widget)
        self.L_21.setMouseTracking(True)
        self.L_21.setAcceptDrops(True)
        self.L_21.setStyleSheet("QLabel {\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"")
        self.L_21.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_21.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_21.setLineWidth(0)
        self.L_21.setText("")
        self.L_21.setScaledContents(False)
        self.L_21.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_21.setWordWrap(True)
        self.L_21.setIndent(0)
        self.L_21.setObjectName("L_21")
        self.gridLayout.addWidget(self.L_21, 5, 4, 1, 1)
        self.L_45 = QtWidgets.QLabel(parent=self.widget)
        self.L_45.setMouseTracking(True)
        self.L_45.setAcceptDrops(True)
        self.L_45.setStyleSheet("QLabel {\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"")
        self.L_45.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_45.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_45.setLineWidth(0)
        self.L_45.setText("")
        self.L_45.setScaledContents(False)
        self.L_45.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_45.setWordWrap(True)
        self.L_45.setIndent(0)
        self.L_45.setObjectName("L_45")
        self.gridLayout.addWidget(self.L_45, 2, 3, 1, 1)
        self.L_48 = QtWidgets.QLabel(parent=self.widget)
        self.L_48.setMouseTracking(True)
        self.L_48.setAcceptDrops(True)
        self.L_48.setStyleSheet("QLabel {\n"
"    background-color: rgb(246, 255, 233);\n"
"}\n"
"")
        self.L_48.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_48.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_48.setLineWidth(0)
        self.L_48.setText("")
        self.L_48.setScaledContents(False)
        self.L_48.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_48.setWordWrap(True)
        self.L_48.setIndent(0)
        self.L_48.setObjectName("L_48")
        self.gridLayout.addWidget(self.L_48, 2, 0, 1, 1)
        self.L_44 = QtWidgets.QLabel(parent=self.widget)
        self.L_44.setMouseTracking(True)
        self.L_44.setAcceptDrops(True)
        self.L_44.setStyleSheet("QLabel {\n"
"    background-color: rgb(246, 255, 233);\n"
"}\n"
"")
        self.L_44.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_44.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_44.setLineWidth(0)
        self.L_44.setText("")
        self.L_44.setScaledContents(False)
        self.L_44.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_44.setWordWrap(True)
        self.L_44.setIndent(0)
        self.L_44.setObjectName("L_44")
        self.gridLayout.addWidget(self.L_44, 2, 4, 1, 1)
        self.L_6 = QtWidgets.QLabel(parent=self.widget)
        self.L_6.setMouseTracking(True)
        self.L_6.setAcceptDrops(True)
        self.L_6.setStyleSheet("QLabel {\n"
"    background-color: rgb(246, 255, 233);\n"
"}\n"
"")
        self.L_6.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_6.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_6.setLineWidth(0)
        self.L_6.setText("")
        self.L_6.setPixmap(QtGui.QPixmap("ui\\Black-Bishop.png"))
        self.L_6.setScaledContents(False)
        self.L_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_6.setWordWrap(True)
        self.L_6.setIndent(0)
        self.L_6.setObjectName("L_6")
        self.gridLayout.addWidget(self.L_6, 14, 5, 1, 1)
        self.L_58 = QtWidgets.QLabel(parent=self.widget)
        self.L_58.setMouseTracking(True)
        self.L_58.setAcceptDrops(True)
        self.L_58.setStyleSheet("QLabel {\n"
"    background-color: rgb(246, 255, 233);\n"
"}\n"
"")
        self.L_58.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_58.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_58.setLineWidth(0)
        self.L_58.setText("")
        self.L_58.setPixmap(QtGui.QPixmap("ui\\White-Knight.png"))
        self.L_58.setScaledContents(False)
        self.L_58.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_58.setWordWrap(True)
        self.L_58.setIndent(0)
        self.L_58.setObjectName("L_58")
        self.gridLayout.addWidget(self.L_58, 0, 6, 1, 1)
        self.L_19 = QtWidgets.QLabel(parent=self.widget)
        self.L_19.setMouseTracking(True)
        self.L_19.setAcceptDrops(True)
        self.L_19.setStyleSheet("QLabel {\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"")
        self.L_19.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_19.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_19.setLineWidth(0)
        self.L_19.setText("")
        self.L_19.setScaledContents(False)
        self.L_19.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_19.setWordWrap(True)
        self.L_19.setIndent(0)
        self.L_19.setObjectName("L_19")
        self.gridLayout.addWidget(self.L_19, 5, 2, 1, 1)
        self.L_47 = QtWidgets.QLabel(parent=self.widget)
        self.L_47.setMouseTracking(True)
        self.L_47.setAcceptDrops(True)
        self.L_47.setStyleSheet("QLabel {\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"")
        self.L_47.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_47.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_47.setLineWidth(0)
        self.L_47.setText("")
        self.L_47.setScaledContents(False)
        self.L_47.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_47.setWordWrap(True)
        self.L_47.setIndent(0)
        self.L_47.setObjectName("L_47")
        self.gridLayout.addWidget(self.L_47, 2, 1, 1, 1)
        self.L_3 = QtWidgets.QLabel(parent=self.widget)
        self.L_3.setMouseTracking(True)
        self.L_3.setAcceptDrops(True)
        self.L_3.setStyleSheet("QLabel {\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"")
        self.L_3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_3.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_3.setLineWidth(0)
        self.L_3.setText("")
        self.L_3.setPixmap(QtGui.QPixmap("ui\\Black-Bishop.png"))
        self.L_3.setScaledContents(False)
        self.L_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_3.setWordWrap(True)
        self.L_3.setIndent(0)
        self.L_3.setObjectName("L_3")
        self.gridLayout.addWidget(self.L_3, 14, 2, 1, 1)
        self.L_7 = QtWidgets.QLabel(parent=self.widget)
        self.L_7.setMouseTracking(True)
        self.L_7.setAcceptDrops(True)
        self.L_7.setStyleSheet("QLabel {\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"")
        self.L_7.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_7.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_7.setLineWidth(0)
        self.L_7.setText("")
        self.L_7.setPixmap(QtGui.QPixmap("ui\\Black-Knight.png"))
        self.L_7.setScaledContents(False)
        self.L_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_7.setWordWrap(True)
        self.L_7.setIndent(0)
        self.L_7.setObjectName("L_7")
        self.gridLayout.addWidget(self.L_7, 14, 6, 1, 1)
        self.L_56 = QtWidgets.QLabel(parent=self.widget)
        self.L_56.setMouseTracking(True)
        self.L_56.setAcceptDrops(True)
        self.L_56.setStyleSheet("QLabel {\n"
"    background-color: rgb(246, 255, 233);\n"
"}\n"
"")
        self.L_56.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_56.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_56.setLineWidth(0)
        self.L_56.setText("")
        self.L_56.setPixmap(QtGui.QPixmap("ui\\White-Pawn.png"))
        self.L_56.setScaledContents(False)
        self.L_56.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_56.setWordWrap(True)
        self.L_56.setIndent(0)
        self.L_56.setObjectName("L_56")
        self.gridLayout.addWidget(self.L_56, 1, 7, 1, 1)
        self.L_13 = QtWidgets.QLabel(parent=self.widget)
        self.L_13.setMouseTracking(True)
        self.L_13.setAcceptDrops(True)
        self.L_13.setStyleSheet("QLabel {\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"")
        self.L_13.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.L_13.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.L_13.setLineWidth(0)
        self.L_13.setText("")
        self.L_13.setPixmap(QtGui.QPixmap("ui\\Black-Pawn.png"))
        self.L_13.setScaledContents(False)
        self.L_13.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_13.setWordWrap(True)
        self.L_13.setIndent(0)
        self.L_13.setObjectName("L_13")
        self.gridLayout.addWidget(self.L_13, 7, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(900, 100, 381, 621))
        self.groupBox.setObjectName("groupBox")
        self.P_1 = QtWidgets.QLabel(parent=self.groupBox)
        self.P_1.setGeometry(QtCore.QRect(0, 0, 381, 81))
        self.P_1.setStyleSheet("QLabel {\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"     background-color: rgb(240, 255, 233);\n"
"}\n"
"\n"
"")
        self.P_1.setObjectName("P_1")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(0, 560, 381, 61))
        self.label_2.setStyleSheet("QLabel {\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"     background-color: rgb(240, 255, 233);\n"
"}\n"
"\n"
"")
        self.label_2.setObjectName("label_2")
        self.P_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.P_2.setGeometry(QtCore.QRect(0, 130, 381, 431))
        self.P_2.setStyleSheet("QLabel {\n"
"    background-color: rgb(240, 255, 233);\n"
"     border-bottom: 2px solid rgb(144, 144, 144);\n"
"  \n"
"}\n"
"")
        self.P_2.setLineWidth(5)
        self.P_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.P_2.setObjectName("P_2")
        self.ForwardLeft = QtWidgets.QPushButton(parent=self.groupBox)
        self.ForwardLeft.setGeometry(QtCore.QRect(0, 60, 101, 71))
        self.ForwardLeft.setToolTipDuration(-1)
        self.ForwardLeft.setStyleSheet("QPushButton {\n"
"    background-color: rgb (204, 216, 197);\n"
"}\n"
"\n"
"")
        self.ForwardLeft.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\Forward-Left.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.ForwardLeft.setIcon(icon)
        self.ForwardLeft.setIconSize(QtCore.QSize(30, 30))
        self.ForwardLeft.setObjectName("ForwardLeft")
        self.ForwrdRight = QtWidgets.QPushButton(parent=self.groupBox)
        self.ForwrdRight.setGeometry(QtCore.QRect(280, 60, 101, 71))
        self.ForwrdRight.setStyleSheet("QPushButton {\n"
"    background-color: rgb (204, 216, 197);\n"
"}\n"
"\n"
"")
        self.ForwrdRight.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui\\Forward-Right.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.ForwrdRight.setIcon(icon1)
        self.ForwrdRight.setIconSize(QtCore.QSize(30, 30))
        self.ForwrdRight.setObjectName("ForwrdRight")
        self.NextRight = QtWidgets.QPushButton(parent=self.groupBox)
        self.NextRight.setGeometry(QtCore.QRect(190, 60, 91, 71))
        self.NextRight.setStyleSheet("QPushButton {\n"
"    background-color: rgb (204, 216, 197);\n"
"}\n"
"\n"
"")
        self.NextRight.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ui\\Next-Right.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.NextRight.setIcon(icon2)
        self.NextRight.setIconSize(QtCore.QSize(30, 30))
        self.NextRight.setObjectName("NextRight")
        self.NextLeft = QtWidgets.QPushButton(parent=self.groupBox)
        self.NextLeft.setGeometry(QtCore.QRect(100, 60, 91, 71))
        self.NextLeft.setStyleSheet("QPushButton {\n"
"    background-color: rgb (204, 216, 197);\n"
"}\n"
"\n"
"")
        self.NextLeft.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ui\\Next-Left.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.NextLeft.setIcon(icon3)
        self.NextLeft.setIconSize(QtCore.QSize(30, 30))
        self.NextLeft.setObjectName("NextLeft")
        self.logo = QtWidgets.QLabel(parent=self.groupBox)
        self.logo.setGeometry(QtCore.QRect(300, 10, 51, 41))
        self.logo.setStyleSheet("QLabel {\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"     background-color: black;\n"
"    color: white;\n"
"}\n"
"\n"
"")
        self.logo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.logo.setObjectName("logo")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(300, 570, 51, 41))
        self.label_3.setStyleSheet("QLabel {\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"     background-color: black;\n"
"    color: white;\n"
"}\n"
"\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.P_2.raise_()
        self.P_1.raise_()
        self.label_2.raise_()
        self.ForwardLeft.raise_()
        self.ForwrdRight.raise_()
        self.NextRight.raise_()
        self.NextLeft.raise_()
        self.logo.raise_()
        self.label_3.raise_()
        self.Main_Logo = QtWidgets.QLabel(parent=self.centralwidget)
        self.Main_Logo.setGeometry(QtCore.QRect(480, 0, 311, 81))
        self.Main_Logo.setStyleSheet("QLabel {\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"     background-color: black;\n"
"    color: white;\n"
"}\n"
"\n"
"")
        self.Main_Logo.setLineWidth(2)
        self.Main_Logo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Main_Logo.setObjectName("Main_Logo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1293, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.P_1.setText(_translate("MainWindow", "Player_1"))
        self.label_2.setText(_translate("MainWindow", "Player_2"))
        self.P_2.setText(_translate("MainWindow", "here the records of the coordinate of every move"))
        self.logo.setText(_translate("MainWindow", "College Logo"))
        self.label_3.setText(_translate("MainWindow", "College Logo"))
        self.Main_Logo.setText(_translate("MainWindow", "Main"))
