# Form implementation generated from reading ui file 'ui/viewHistory.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_viewHistoryx(object):
    def setupUi(self, viewHistoryx):
        viewHistoryx.setObjectName("viewHistoryx")
        viewHistoryx.resize(1000, 700)
        viewHistoryx.setMinimumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\img/app.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        viewHistoryx.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(viewHistoryx)
        self.gridLayout.setObjectName("gridLayout")
        self.chessOutput = QtWidgets.QLabel(parent=viewHistoryx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.chessOutput.sizePolicy().hasHeightForWidth())
        self.chessOutput.setSizePolicy(sizePolicy)
        self.chessOutput.setStyleSheet("background-color: white; border: 1px solid gray;")
        self.chessOutput.setText("")
        self.chessOutput.setObjectName("chessOutput")
        self.gridLayout.addWidget(self.chessOutput, 0, 0, 4, 1)
        self.groupBox = QtWidgets.QGroupBox(parent=viewHistoryx)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.matchList = QtWidgets.QListWidget(parent=self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.matchList.sizePolicy().hasHeightForWidth())
        self.matchList.setSizePolicy(sizePolicy)
        self.matchList.setMinimumSize(QtCore.QSize(250, 150))
        self.matchList.setObjectName("matchList")
        self.verticalLayout.addWidget(self.matchList)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loadButton = QtWidgets.QPushButton(parent=self.groupBox)
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout.addWidget(self.loadButton)
        self.resetButton = QtWidgets.QPushButton(parent=self.groupBox)
        self.resetButton.setObjectName("resetButton")
        self.horizontalLayout.addWidget(self.resetButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addWidget(self.groupBox, 0, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=viewHistoryx)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.movesList = QtWidgets.QListWidget(parent=self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.movesList.sizePolicy().hasHeightForWidth())
        self.movesList.setSizePolicy(sizePolicy)
        self.movesList.setMinimumSize(QtCore.QSize(250, 200))
        self.movesList.setObjectName("movesList")
        self.verticalLayout_2.addWidget(self.movesList)
        self.gridLayout.addWidget(self.groupBox_2, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 1, 1, 1)
        self.returnButton = QtWidgets.QPushButton(parent=viewHistoryx)
        self.returnButton.setMinimumSize(QtCore.QSize(100, 30))
        self.returnButton.setObjectName("returnButton")
        self.gridLayout.addWidget(self.returnButton, 3, 1, 1, 1, QtCore.Qt.AlignmentFlag.AlignRight)

        self.retranslateUi(viewHistoryx)
        QtCore.QMetaObject.connectSlotsByName(viewHistoryx)

    def retranslateUi(self, viewHistoryx):
        _translate = QtCore.QCoreApplication.translate
        viewHistoryx.setWindowTitle(_translate("viewHistoryx", "History"))
        self.groupBox.setTitle(_translate("viewHistoryx", "Saved Matches"))
        self.loadButton.setText(_translate("viewHistoryx", "Load Match"))
        self.resetButton.setText(_translate("viewHistoryx", "Reset"))
        self.groupBox_2.setTitle(_translate("viewHistoryx", "Moves List"))
        self.returnButton.setText(_translate("viewHistoryx", "Return"))
